// 200 câu quotes ý nghĩa cho trẻ em
// Các chủ đề: Tài chính, Tiết kiệm, Học hành, Lễ phép, Kiến thức, Năm mới, Gia đình

export const QUOTES = [
  // ===== TÀI CHÍNH & TIẾT KIỆM (1-40) =====
  "Tiền tiết kiệm hôm nay là cơ hội cho tương lai của con!",
  "Mỗi đồng tiền nhỏ tích lũy lại sẽ thành khoản lớn sau này.",
  "Ăn phải dành, có phải kiệm - tiết kiệm là thói quen tốt!",
  "Khéo ăn thì no, khéo co thì ấm.",
  "Buôn tàu bán bè không bằng ăn dè hà tiện.",
  "Của bền tại người - biết giữ gìn thì của sẽ bền.",
  "Tích tiểu thành đại - góp gió thành bão!",
  "Một xu cũng là tiền, hãy trân trọng từng đồng nhỏ.",
  "Đừng xài hết, hãy để dành một ít cho ngày mai!",
  "Tiết kiệm không phải là keo kiệt, mà là biết chi tiêu hợp lý.",
  "Người khôn ngoan biết tiết kiệm từ khi còn nhỏ.",
  "Tiền không mọc trên cây, hãy trân trọng công sức làm ra nó.",
  "Để dành hôm nay, an tâm ngày mai!",
  "Góp nhặt từng chút, rồi sẽ thành nhiều.",
  "Ai biết tiết kiệm, người ấy sẽ giàu có.",
  "Đồng tiền đi liền khúc ruột - hãy chi tiêu cẩn thận!",
  "Tiết kiệm là bước đầu của sự giàu có.",
  "Hãy hỏi ba mẹ trước khi mua đồ nhé!",
  "Muốn mua gì, hãy suy nghĩ: Mình có thực sự cần không?",
  "Của cải là mồ hôi, công sức - đừng lãng phí!",
  "Tiền lì xì là tình cảm của người lớn, hãy trân trọng!",
  "Gửi tiền cho ba mẹ giữ là cách tiết kiệm thông minh.",
  "Tiền để dành sẽ giúp con mua được thứ lớn hơn sau này.",
  "Chi tiêu có kế hoạch, tương lai sẽ tươi sáng!",
  "Biết đủ là giàu - không cần phải có tất cả mọi thứ.",
  "Hãy phân biệt thứ CẦN và thứ MUỐN nhé!",
  "Mua ít đồ chơi, để dành tiền học hành.",
  "Tiền tiết kiệm là người bạn đồng hành trong tương lai.",
  "Có công mài sắt, có ngày nên kim - kiên trì tiết kiệm sẽ có kết quả!",
  "Cha mẹ làm việc vất vả để kiếm tiền, con hãy biết quý trọng.",
  "Một đồng tiết kiệm hôm nay, một bước tiến cho ngày mai.",
  "Đừng so sánh với bạn bè - mỗi người có hoàn cảnh riêng.",
  "Hãy biết ơn những gì mình đang có.",
  "Tiền bạc quan trọng, nhưng tình cảm còn quý hơn.",
  "Học cách quản lý tiền từ nhỏ, lớn lên sẽ thành công.",
  "Tiết kiệm điện, tiết kiệm nước cũng là tiết kiệm tiền!",
  "Đồ cũ vẫn dùng được, không cần mua đồ mới liên tục.",
  "Hãy lập mục tiêu tiết kiệm và cố gắng đạt được!",
  "Chia sẻ với người khó khăn hơn mình là điều tuyệt vời.",
  "Tiền không mang lại hạnh phúc, nhưng giúp cuộc sống dễ dàng hơn.",

  // ===== HỌC HÀNH & KIẾN THỨC (41-80) =====
  "Học như thuyền ngược nước, không tiến ắt lùi.",
  "Có công mài sắt, có ngày nên kim.",
  "Đi một ngày đàng, học một sàng khôn.",
  "Học không biết chán, dạy người không biết mỏi.",
  "Tri thức là chìa khóa mở cửa tương lai.",
  "Học, học nữa, học mãi!",
  "Không có học sinh yếu, chỉ có học sinh chưa chăm.",
  "Đọc sách mỗi ngày, kiến thức sẽ đầy!",
  "Hỏi là cách học nhanh nhất - đừng ngại hỏi thầy cô!",
  "Thất bại là mẹ thành công - đừng sợ sai!",
  "Kiến thức là kho báu không ai lấy được.",
  "Học giỏi để báo đáp công ơn cha mẹ.",
  "Chữ là thầy, nghề là bạn.",
  "Dốt đến đâu, học lâu cũng biết.",
  "Học một biết mười - hãy tư duy sáng tạo!",
  "Muốn biết phải hỏi, muốn giỏi phải học.",
  "Sách là người thầy vĩ đại nhất.",
  "Học hành chăm chỉ, tương lai tươi sáng.",
  "Bé học hôm nay, lớn thành tài ngày mai!",
  "Học để hiểu biết, không chỉ để lấy điểm.",
  "Mỗi ngày tiến bộ một chút, rồi sẽ giỏi!",
  "Chớ bỏ ngày nào không học - kiến thức cần tích lũy.",
  "Học từ sai lầm để không lặp lại.",
  "Thầy cô như cha mẹ thứ hai, hãy kính trọng!",
  "Bạn bè tốt giúp nhau học tập tiến bộ.",
  "Tò mò là bước đầu của khám phá!",
  "Hãy đặt câu hỏi 'Tại sao?' mỗi ngày.",
  "Viết chữ đẹp thể hiện người có tâm.",
  "Làm bài tập đầy đủ là trách nhiệm của học sinh.",
  "Học ngoại ngữ mở ra cánh cửa thế giới.",
  "Toán học rèn luyện tư duy logic.",
  "Đọc truyện cũng là học - học về cuộc sống!",
  "Sáng tạo là biết kết hợp những điều đã học.",
  "Không ai sinh ra đã giỏi, tất cả đều phải học!",
  "Mỗi ngày đến trường là một ngày vui!",
  "Học để làm người tốt, không chỉ để thông minh.",
  "Kiên nhẫn là chìa khóa của thành công học tập.",
  "Ghi chép cẩn thận, nhớ lâu hơn!",
  "Ôn bài trước khi ngủ, sáng dậy nhớ rõ hơn.",
  "Học nhóm giúp nhau tiến bộ nhanh hơn!",

  // ===== LỄ PHÉP & CÁCH CƯ XỬ (81-120) =====
  "Lời chào cao hơn mâm cỗ - hãy chào hỏi lễ phép!",
  "Kính trên nhường dưới là nếp sống đẹp.",
  "Ơn ai một chút chớ quên.",
  "Lễ phép với người lớn, nhường nhịn với em nhỏ.",
  "Ăn trông nồi, ngồi trông hướng.",
  "Đi thưa về gửi - báo với ba mẹ khi đi đâu.",
  "Gọi dạ bảo vâng - lễ phép với người lớn.",
  "Tôn trọng người khác, người khác sẽ tôn trọng mình.",
  "Nói lời cảm ơn khi được giúp đỡ.",
  "Xin lỗi khi làm sai - đó là dũng cảm!",
  "Không nói dối - thật thà là đức tính tốt.",
  "Biết xếp hàng, không chen lấn.",
  "Nhường ghế cho người già trên xe buýt.",
  "Giúp đỡ bạn bè khi họ gặp khó khăn.",
  "Không chê bai, chọc ghẹo người khác.",
  "Lắng nghe khi người khác nói.",
  "Không ngắt lời người lớn đang nói chuyện.",
  "Ăn uống từ tốn, không nói khi miệng có thức ăn.",
  "Dọn dẹp đồ chơi sau khi chơi xong.",
  "Để dép ngay ngắn khi vào nhà.",
  "Chào hỏi thầy cô và người lớn mỗi ngày.",
  "Chia sẻ đồ chơi với bạn bè và em nhỏ.",
  "Kiên nhẫn chờ đợi đến lượt mình.",
  "Không tranh giành với bạn.",
  "Nói năng nhẹ nhàng, không la hét.",
  "Giữ gìn vệ sinh công cộng.",
  "Không vứt rác bừa bãi.",
  "Biết nói 'Làm ơn' khi nhờ ai đó.",
  "Cư xử đẹp ở nơi công cộng.",
  "Tôn trọng quy tắc và nội quy.",
  "Không chạy nhảy trong lớp học.",
  "Mặc quần áo gọn gàng, sạch sẽ.",
  "Đúng giờ là thể hiện sự tôn trọng.",
  "Giữ lời hứa - đã nói là phải làm.",
  "Không lấy đồ của người khác khi chưa xin phép.",
  "Xin phép ba mẹ trước khi làm gì quan trọng.",
  "Nhận lỗi khi sai, không đổ lỗi cho người khác.",
  "Tự làm những việc mình có thể.",
  "Giúp ba mẹ việc nhà nhỏ mỗi ngày.",
  "Yêu thương động vật và cây cỏ.",

  // ===== GIA ĐÌNH & YÊU THƯƠNG (121-160) =====
  "Gia đình là nơi tình yêu bắt đầu.",
  "Công cha như núi Thái Sơn, nghĩa mẹ như nước trong nguồn chảy ra.",
  "Anh em như thể tay chân.",
  "Chị ngã em nâng - anh chị em phải thương nhau.",
  "Một giọt máu đào hơn ao nước lã.",
  "Gia đình là tổ ấm của mỗi người.",
  "Con cái khôn ngoan, vẻ vang cha mẹ.",
  "Cây có cội, sông có nguồn - nhớ ơn ông bà tổ tiên.",
  "Anh em thuận hòa là nhà có phúc.",
  "Yêu thương gia đình là hạnh phúc lớn nhất.",
  "Ba mẹ là người yêu thương con vô điều kiện.",
  "Ông bà là kho tàng của gia đình.",
  "Hãy ôm ba mẹ mỗi ngày!",
  "Cùng ăn cơm với gia đình là khoảnh khắc quý giá.",
  "Anh chị em là bạn suốt đời.",
  "Chia sẻ niềm vui với gia đình, nỗi buồn sẽ vơi đi.",
  "Nhà là nơi con luôn được chào đón.",
  "Hãy kể cho ba mẹ nghe về ngày của con.",
  "Giúp em nhỏ cũng là thương yêu gia đình.",
  "Khi buồn, hãy tìm đến ba mẹ - họ luôn ở đây!",
  "Gia đình có thể nghèo tiền, nhưng giàu tình thương.",
  "Hãy nói 'Con yêu ba mẹ' thường xuyên hơn.",
  "Kỷ niệm gia đình là tài sản vô giá.",
  "Cùng gia đình du lịch là niềm vui lớn.",
  "Bữa cơm gia đình ấm cúng hơn bất kỳ nhà hàng nào.",
  "Hãy lắng nghe câu chuyện của ông bà.",
  "Truyền thống gia đình cần được gìn giữ.",
  "Yêu thương là cho đi, không đòi hỏi.",
  "Gia đình là nơi nuôi dưỡng tâm hồn.",
  "Kính trọng ba mẹ là đạo làm con.",
  "Em bé trong nhà là niềm vui của cả gia đình.",
  "Hãy dành thời gian cho gia đình mỗi ngày.",
  "Cảm ơn ba mẹ vì những gì họ làm cho con.",
  "Gia đình là điểm tựa vững chắc nhất.",
  "Khi lớn lên, hãy chăm sóc ba mẹ như họ đã chăm con.",
  "Tình cảm gia đình là vĩnh cửu.",
  "Hãy tự hào về gia đình của mình.",
  "Gia đình hạnh phúc là nền tảng của xã hội.",
  "Nhớ gọi điện cho ông bà khi xa nhà.",
  "Gia đình là nơi ta thuộc về.",

  // ===== NĂM MỚI & TẾT (161-200) =====
  "Năm mới đến, niềm vui đến, hạnh phúc đến!",
  "Chúc con năm mới học giỏi, chăm ngoan!",
  "Tết là dịp sum họp gia đình.",
  "Mùa xuân về, vạn vật tươi mới.",
  "Năm mới, ước mơ mới, cố gắng mới!",
  "Xuân sang, hoa nở, lòng người rộn ràng.",
  "Tết đến xuân về, con cháu sum vầy.",
  "Năm mới bình an, vạn sự như ý!",
  "Mừng tuổi mới, khôn lớn thêm một chút.",
  "Tết là dịp cảm ơn những người thương yêu.",
  "Pháo hoa rực rỡ, năm mới tươi sáng!",
  "Áo mới ngày Tết, niềm vui trẻ thơ.",
  "Bánh chưng xanh, dưa hành - Tết Việt Nam.",
  "Mai vàng nở rộ, xuân về khắp nơi.",
  "Cầu chúc năm mới an khang thịnh vượng!",
  "Giao thừa là khoảnh khắc thiêng liêng.",
  "Năm mới, hãy đặt mục tiêu và cố gắng!",
  "Lì xì là lời chúc may mắn từ người lớn.",
  "Tết là dịp thể hiện lòng biết ơn.",
  "Mùa xuân tràn đầy hy vọng.",
  "Chúc ông bà sống lâu trăm tuổi!",
  "Chúc ba mẹ năm mới nhiều sức khỏe!",
  "Năm mới, con sẽ ngoan hơn, giỏi hơn!",
  "Xuân về, cây cối đâm chồi nảy lộc.",
  "Tết là thời gian nghỉ ngơi và vui chơi.",
  "Năm mới, tình yêu thương lan tỏa.",
  "Hoa đào hoa mai, xuân về rực rỡ.",
  "Câu đối đỏ, tranh Tết - nét đẹp Việt Nam.",
  "Năm mới, hãy tha thứ và bỏ qua chuyện cũ.",
  "Múa lân rộn ràng đón xuân sang.",
  "Tết là dịp để yêu thương nhiều hơn.",
  "Năm Tỵ - năm con Rắn, thông minh và nhanh nhẹn!",
  "Rắn tượng trưng cho sự khôn ngoan.",
  "Xuân về, lòng người ấm áp.",
  "Năm mới, hãy biết ơn những gì mình có.",
  "Tết cổ truyền - di sản văn hóa Việt Nam.",
  "Chúc năm mới phúc lộc đầy nhà!",
  "Mùa xuân là mùa của sự khởi đầu.",
  "Năm mới tài lộc, bình an, may mắn!",
  "Xuân sang, niềm vui bất tận - Chúc mừng năm mới!",
];

// Hàm lấy quote ngẫu nhiên
export const getRandomQuote = (): string => {
  const index = Math.floor(Math.random() * QUOTES.length);
  return QUOTES[index];
};

// Hàm lấy quote theo session (thay đổi mỗi lần mở tab)
let currentQuoteIndex = Math.floor(Math.random() * QUOTES.length);
export const getSessionQuote = (): string => {
  return QUOTES[currentQuoteIndex];
};

export const refreshSessionQuote = (): string => {
  currentQuoteIndex = Math.floor(Math.random() * QUOTES.length);
  return QUOTES[currentQuoteIndex];
};
